# -*- coding: utf-8 -*-
"""ml final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CaPRlmwcRe368U6GkAinRILchuFF5BJX
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()

rec = pd.read_csv("recommendations3.csv")

rec.head()

ante = set(rec['antecedents'])
ante

d = {}
l =[]
for i in ante:
  df = rec[rec['antecedents'] == i]
  d[i] = list(df['consequents'].unique())

d

i = input("Enter what you want: ")
print(d[i])











